# Build-tree and relocated install-tree consumer/model-read regressions.
# Only CMake and the native C++ consumer are used. No Python dependency.
cmake_minimum_required(VERSION 3.20)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." REALPATH)
if(IS_SYMLINK "${ROOT}/build" OR NOT EXISTS "${ROOT}/build/gladesConfig.cmake")
    message(FATAL_ERROR "Configure/build the CPU library in a real build/ directory first")
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(RUN "${ROOT}/build/package-consumer-${suffix}")
if(EXISTS "${RUN}" OR IS_SYMLINK "${RUN}")
    message(FATAL_ERROR "Evidence directory collision")
endif()
file(MAKE_DIRECTORY "${RUN}")
set(ENV{GLADES_MODEL_VERIFY_FILES} 0)
message(STATUS "Package regression evidence: ${RUN}")

function(run cwd)
    execute_process(COMMAND ${ARGN} WORKING_DIRECTORY "${cwd}" TIMEOUT 120
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(APPEND "${RUN}/commands.log" "\ncwd=[${cwd}]\n")
    foreach(arg IN LISTS ARGN)
        file(APPEND "${RUN}/commands.log" "  [${arg}]\n")
    endforeach()
    file(APPEND "${RUN}/commands.log" "${output}${error}\nexit=${result}\n")
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Command failed (${result}): ${ARGN}\n${output}\n${error}")
    endif()
    set(OUTPUT "${output}" PARENT_SCOPE)
endfunction()
function(snapshot directory output)
    file(GLOB_RECURSE files LIST_DIRECTORIES FALSE RELATIVE "${directory}" "${directory}/*")
    set(hashes "")
    foreach(file IN LISTS files)
        file(SHA256 "${directory}/${file}" hash)
        string(APPEND hashes "${hash}  ${file}\n")
    endforeach()
    set(${output} "${hashes}" PARENT_SCOPE)
endfunction()
function(prediction output variable)
    string(REGEX MATCH "(^|\n)PRED [^\r\n]+" match "${output}")
    if(NOT match)
        message(FATAL_ERROR "Missing prediction line: ${output}")
    endif()
    string(STRIP "${match}" match)
    set(${variable} "${match}" PARENT_SCOPE)
endfunction()
function(replace_required file before after)
    file(READ "${file}" text)
    string(FIND "${text}" "${before}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Fixture mutation did not match: ${file}: ${before}")
    endif()
    string(REPLACE "${before}" "${after}" text "${text}")
    file(WRITE "${file}" "${text}")
endfunction()

foreach(kind build install)
    if(kind STREQUAL "build")
        set(package "${ROOT}/build")
    else()
        run("${RUN}" "${CMAKE_COMMAND}" --install "${ROOT}/build" --prefix "${RUN}/stage")
        file(RENAME "${RUN}/stage" "${RUN}/relocated-prefix")
        set(package "${RUN}/relocated-prefix/share/glades/cmake")
        file(GLOB exports "${package}/*.cmake")
        foreach(export IN LISTS exports)
            file(READ "${export}" contents)
            foreach(forbidden include Backend)
                string(FIND "${contents}" "${ROOT}/${forbidden}" found)
                if(NOT found EQUAL -1)
                    message(FATAL_ERROR "Relocated export retains source-tree path: ${export}")
                endif()
            endforeach()
        endforeach()
    endif()
    set(build "${RUN}/${kind}-consumer")
    run("${RUN}" "${CMAKE_COMMAND}" -S "${ROOT}/tests/package-consumer" -B "${build}" "-Dglades_DIR=${package}")
    run("${RUN}" "${CMAKE_COMMAND}" --build "${build}" --parallel 2)
    set(binary "${build}/package_consumer")
    set(writer "${RUN}/${kind}-writer")
    file(MAKE_DIRECTORY "${writer}")
    run("${writer}" "${binary}" create fixture)
    prediction("${OUTPUT}" expected)
    set(original "${writer}/database/models/fixture")
    set(model "${RUN}/${kind}-relocated model")
    file(MAKE_DIRECTORY "${model}")
    file(COPY "${original}/" DESTINATION "${model}")
    set(reader "${RUN}/${kind}-empty-read-only-cwd")
    file(MAKE_DIRECTORY "${reader}")
    snapshot("${model}" before)
    file(CHMOD_RECURSE "${model}" FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
        DIRECTORY_PERMISSIONS OWNER_READ OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
    file(CHMOD "${reader}" PERMISSIONS OWNER_READ OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
    foreach(path "${model}" "${model}/")
        run("${reader}" "${binary}" read "${path}")
        prediction("${OUTPUT}" actual)
        if(NOT actual STREQUAL expected)
            message(FATAL_ERROR "Prediction changed after relocation/read-only load")
        endif()
    endforeach()
    run("${reader}" "${binary}" wrong-shape "${model}")
    snapshot("${model}" after)
    file(GLOB cwd_files "${reader}/*")
    if(NOT before STREQUAL after OR cwd_files)
        message(FATAL_ERROR "Reader mutated model or empty CWD")
    endif()
    run("${reader}" "${binary}" reject relative/model)
    run("${reader}" "${binary}" reject "${RUN}/missing-package")
    set(link "${RUN}/${kind}-symlink")
    file(CREATE_LINK "${model}" "${link}" SYMBOLIC)
    run("${reader}" "${binary}" reject "${link}")
    run("${reader}" "${binary}" reject "${link}/")
    foreach(case manifest-missing weights-missing architecture-missing magic checksum truncated metadata architecture-size file-symlink version net-type)
        set(bad "${RUN}/${kind}-${case}")
        file(MAKE_DIRECTORY "${bad}")
        file(COPY "${original}/" DESTINATION "${bad}")
        set(manifest "${bad}/manifest.txt")
        set(weights "${bad}/weights.bin")
        if(case STREQUAL "manifest-missing")
            file(REMOVE "${manifest}")
        elseif(case STREQUAL "weights-missing")
            file(REMOVE "${weights}")
        elseif(case STREQUAL "architecture-missing")
            file(REMOVE "${bad}/nninfo.csv")
        elseif(case STREQUAL "magic")
            replace_required("${manifest}" GLADES_MODEL BROKEN_MODEL)
        elseif(case STREQUAL "version")
            replace_required("${manifest}" "version=3\n" "version=4\n")
        elseif(case STREQUAL "net-type")
            replace_required("${manifest}" "netType=0\n" "netType=1\n")
        elseif(case STREQUAL "checksum" OR case STREQUAL "truncated")
            run("${RUN}" "${binary}" corrupt "${case}" "${weights}")
        elseif(case STREQUAL "metadata")
            file(READ "${manifest}" contents)
            string(REGEX REPLACE "\nweights\\.[^\n]*" "" changed "${contents}")
            if(changed STREQUAL contents)
                message(FATAL_ERROR "Missing weights metadata in fixture")
            endif()
            file(WRITE "${manifest}" "${changed}")
        elseif(case STREQUAL "architecture-size")
            file(APPEND "${bad}/nninfo.csv" "\n")
        elseif(case STREQUAL "file-symlink")
            file(REMOVE "${weights}")
            file(CREATE_LINK "${original}/weights.bin" "${weights}" SYMBOLIC)
        endif()
        run("${reader}" "${binary}" reject "${bad}")
    endforeach()
    # Check again after negative reads, not just the successful load.
    snapshot("${model}" after)
    file(GLOB cwd_files "${reader}/*")
    if(NOT before STREQUAL after OR cwd_files)
        message(FATAL_ERROR "Negative reads mutated model or empty CWD")
    endif()
    file(APPEND "${RUN}/results.txt" "PASS ${kind}: exports, relocation, read-only deterministic load, strict failures\n")
    message(STATUS "PASS ${kind}: exports, relocation, read-only deterministic load, strict failures")
endforeach()
file(APPEND "${RUN}/results.txt" "PASS public package regression; Python not used\n")
message(STATUS "PASS public package regression")
